name: popular_wine_classifier
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  tflite: ^1.1.2
  image_picker: ^0.6.6+5
  camera: ^0.5.8+11
  image: ^2.1.18
  path_provider: ^1.6.21
  path: ^1.7.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Cedarville
      fonts:
        - asset: assets/fonts/CedarvilleCursive-Regular.ttf
    - family: Charmonman
      fonts:
        - asset: assets/fonts/Charmonman-Regular.ttf
        - asset: assets/fonts/Charmonman-Bold.ttf
    - family: Cinzel
      fonts:
        - asset: assets/fonts/Cinzel-Regular.ttf
        - asset: assets/fonts/Cinzel-Medium.ttf
        - asset: assets/fonts/Cinzel-SemiBold.ttf
        - asset: assets/fonts/Cinzel-Bold.ttf
        - asset: assets/fonts/Cinzel-ExtraBold.ttf
        - asset: assets/fonts/Cinzel-Black.ttf
    - family: CinzelDecorative
      fonts:
        - asset: assets/fonts/CinzelDecorative-Regular.ttf
        - asset: assets/fonts/CinzelDecorative-Bold.ttf
        - asset: assets/fonts/CinzelDecorative-Black.ttf
    - family: MarcellusSC
      fonts:
        - asset: assets/fonts/MarcellusSC-Regular.ttf
    - family: NixieOne
      fonts:
        - asset: assets/fonts/NixieOne-Regular.ttf
    - family: Tangerine
      fonts:
        - asset: assets/fonts/Tangerine-Regular.ttf
        - asset: assets/fonts/Tangerine-Bold.ttf
